### ISSUE TITLE
webtrees

### ISSUE THREAD

**Issue by radoeka** [derbenx/nextcloud-familytree#3]
Nice to see this kind (family tree) of application become available for Nextcloud.

Recently I stumbled over https://webtrees.net/ would it be possible to use this in combination with Nextcloud?
Is it perhaps possible to integrate this app into Nextcloud?

**Comment by derbenx** [comment]
"All you need to use it is a website with PHP and MySQL installed."

Sounds like it could be done, but I'd take some work to get it all working properly under nextcloud. Any ajax calls need to be converted and probably several other changes to ensure compatibility. I haven't looked at the code layout or anything. Anyone who knows PHP, SQL and nextcloud app formats should be able to do this eventually. The problem with doing this, is any decent updates you'd have to do the conversion all over again or line by line compare/swap. And because it uses PHP and SQL, you'd want any of the security patches ASAP!

My version was much easier to convert to nextcloud, as it runs in memory (via javascript, no php or SQL needed**) and saves the tree directly to file. There's not much risk to security, it doesn't touch PHP or SQL databases. Loading in a bad tree, would perhaps just require a page reload, at most, close the tab and re-open it.

** My non nextcloud version you could save the page as HTML and open it offline in a browser and it would still work. ;) The nextcloud version could do the same thing if nextcloud code lets you open a saved page offline... I never tried.

**Comment by radoeka** [comment]
@derbenx just wanted to let you know that it exist.  
Perhaps in case it is/was possible to (re-)use the data the from that project (not necessarily the webtrees website.
The other one is [Gramps](https://gramps-project.org).  With this it is possible to dump the data that results in an static website with files.  It has a sister project that provides a dynamic website.
I'll follow your familytree endeavour, be curious what it will become.
